// <auto-generated />
namespace QueryFramework.Internal
{
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	///	This API supports the QueryFramework infrastructure and is not intended to be used
	///	directly from your code. This API may change or be removed in future releases.
	/// </summary>
	public static class SqlServerStrings
	{
		private static readonly ResourceManager _resourceManager
			= new ResourceManager("QueryFramework.SqlServer2012.Properties.SqlServerStrings", typeof(SqlServerStrings).GetTypeInfo().Assembly);

		private static string GetString(string name, params string[] formatterNames)
		{
			var value = _resourceManager.GetString(name);

			if (formatterNames != null)
			{
				for (var i = 0; i < formatterNames.Length; i++)
				{
					value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
				}
			}

			return value;
		}
	}
}
